# MerMer Default Config

title = "EnvDashboard"

[base]
folder = "MerMer-framework"
static = "./build/frontend/"
debug = false

[blockchain]
type = "ethereum"

[database]
type = "firebase"

[env]
pollutions = [
  "AQI",
  "SO2",
  "CO",
  "O3",
  "PM10",
  "PM2.5",
  "NO2",
  "NOX",
  "NO"
]

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo",
  "get | /weather | Bot.OpenData.summary",
  "get | /aqiStations | Bot.OpenData.aqiStations",
  "get | /weatherStations | Bot.OpenData.weatherStations",
  "get | /polltionTypes | Bot.OpenData.pollutionTypes",
  "get | /pollution/24h | Bot.OpenData.pollution24h"
]